### ISSUE TITLE
Plugin fail

### ISSUE THREAD

**Issue by thonixx** [phoenix2/phoenix#1]
Whenever I start phoenix I get the errors with no plugins found.

Here are the lines:
[13:22:25] Failed to load plugin "phatk2"  
[13:22:25] Failed to load plugin "opencl"   

The plugins are there and strace shows the correct folder with correct files but phoenix can't load any plugins.
My system: Ubuntu 12.10, 64bit, latest python (2.7)

**Comment by asukharev** [comment]
phatk2 and opencl modules uses python-pyopencl package.
Ubuntu 12.10 have problems with it (https://bugs.launchpad.net/ubuntu/+source/pyopencl/+bug/1048036).

**Comment by thonixx** [comment]
Thanks for the bug URL. I will look there.
